# Generated by Django 5.2.13 on 2026-06-03 12:27
# Hand-edited: adding a unique field to a table with existing rows takes three
# steps, because AddField's default is evaluated ONCE and reused for every
# existing row — which violates unique=True as soon as there are 2+ rows.

import uuid
from django.db import migrations, models


def backfill_public_ids(apps, schema_editor):
    """Give every existing order its own UUID (step 2 of 3)."""
    # apps.get_model gives the model AS OF THIS MIGRATION, not as models.py
    # looks today. Never import the real model into a migration — a future
    # field change would break this file retroactively.
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.all():
        order.public_id = uuid.uuid4()
        order.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_archivedorder_recentorder'),
    ]

    operations = [
        # 1. add the column with NO unique constraint. Every existing row gets
        #    the same placeholder UUID here, and that is fine for now.
        migrations.AddField(
            model_name='order',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),

        # 2. replace those duplicates with one distinct UUID per row
        migrations.RunPython(
            backfill_public_ids,
            reverse_code=migrations.RunPython.noop,
        ),

        # 3. values are distinct now, so the constraint can be applied
        migrations.AlterField(
            model_name='order',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),

        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
