# Generated by Django 6.0.4 on 2026-04-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='spice_level',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
