# Generated by Django 5.2.13 on 2026-05-04 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.menuitem')),
                ('size_ml', models.IntegerField()),
                ('is_carbonated', models.BooleanField(default=False)),
            ],
            bases=('menu.menuitem',),
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='spice_level',
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.menuitem')),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('spice_level', models.IntegerField(default=0)),
            ],
            bases=('menu.menuitem',),
        ),
    ]
